# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Lane For Android Firebase App Distribution "
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
    app: "1:495839621726:android:f0766ee72061a64893facf",
    firebase_cli_token: "1//03UB9c6JaYBq0CgYIARAAGAMSNwF-L9Ir7JaD0sLmwakWQlLwz0f1lfXT1acCU0Sn1XysRhtSQH3UZe0-yA4POATgo9YdDKO7lnM",
    android_artifact_type: "APK",
    android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
    testers: "tahahamada2901@gmail.com, salsabilsayed783@gmail.com , omayamahamada123@gmail.com, abdelmonemhend87@gmail.com",
    release_notes: "First Fastlane Firebase Distribution"
  )
  end
end
